clip : 50.0
teacher_forcing_ratio : 1.0
learning_rate : 0.00001
decoder_learning_ratio : 5.0
n_iteration : 10000
print_every : 10
save_every :  3000


model:
  model_name : 'cb_model'
  attn_model : 'dot'
  #``attn_model = 'general'``
  #``attn_model = 'concat'``
  hidden_size : 500
  encoder_n_layers : 2
  decoder_n_layers : 2
  dropout : 0.2
  batch_size : 64
  checkpoint_iter : 4000
  attention : True